# The URL the site will be built for

# this variable has to be set but it is not used
# inside the templates (end in '/')
base_url = "https://nordicesmhub.github.io/NICEST2-final-events/"

# When adapting the title, do not forget to also adjust base_url above
title = "NeIC NICEST2 Final Project Meeting"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "cheerfully-light"

# Whether external links are to be opened in a new tab
external_links_target_blank = true

[extra]

navigation = [
    { name = "About", target = "" },
    { name = "Code of conduct", target = "code-of-conduct/" },
]

twitter_image = "https://raw.githubusercontent.com/NordicESMhub/nicest2/master/img/avatar-nicest2.png"

# you can place multiple logos like this
# the image file(s) need to be placed in content/logos
logos = [
   { alt_text = "NeIC logo", target_url = "https://neic.no", image = "neic_logo.png" },
   { alt_text = "NICEST2 logo", target_url = "https://nordicesmhub.github.io/nicest2/", image = "nicest2.png" }
]

# adapt this
registration_link = "https://forms.gle/QQx7Pi4J7nwNXnrM8"
source_repo = "https://github.com/NordicESMHub/NICEST2-final-events"

# uncomment as soon as registration opens
# registration_is_open = true

# uncomment as soon as registration closes
registration_is_closed = true
